name: Setup Fontist
description: 🔠 Install Fontist for GitHub Actions

branding:
  icon: play
  color: purple

inputs:
  fontist-version:
    default: latest
  fontist-token:
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  setup-ruby-token:
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

outputs:
  fontist-version: {}
  cache-hit: {}

runs:
  using: node20
  main: dist/main.js
