name: Setup Fontist
description: 🔠 Install Fontist for GitHub Actions

branding:
  icon: play
  color: purple

inputs:
  fontist-token:
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  fontist-version:
    default: latest

outputs:
  fontist-version:
    value: ${{ steps.setup-fontist.outputs.fontist-version }}
  cache-hit:
    value: ${{ steps.setup-fontist.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
      env:
        GITHUB_PATH: ${{ runner.temp }}/GITHUB_PATH
    - id: setup-fontist
      uses: ./setup-fontist
      with: ${{ inputs }}
