inputs:
  fontist-version:
    default: "1.19.0"

runs:
  using: composite
  steps:
    - shell: bash
      run: gem install fontist --version "$(printenv INPUT_FONTIST-VERSION)"
      env:
        INPUT_FONTIST-VERSION: ${{ inputs.fontist-version }}