name: Setup Fontist
description: 🔠 Install Fontist for GitHub Actions

branding:
  icon: play
  color: purple

inputs:
  fontist-version:
    description: The version of Fontist to install. This can be an exact version lile '1.10.0' or a semver range such as '1.x' or '~1.15.0'. The default value is 'latest'.
    default: latest
  fontist-token:
    description: The GitHub token to use when fetching the version list from fontist/fontist. You shouldn't have to touch this. The default is the 'github.token' if you're on github.com or unauthenticated (rate limited) if you're not on github.com.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  cache:
    description: Whether or not to use @actions/cache to cache things in the GitHub workflow cache. This is enabled by default.
    default: true
  cache-dependency-path:
    description: A multiline list of globs to use to derive the '~/.fontist' cache key. The default is 'manifest.yml' and 'manifest.yaml'. If no files are matched at runtime then the '~/.fontist' folder will not be cached.
    default: manifest.y{a,}ml

outputs:
  fontist-version:
    description: The version of Fontist that was installed. This will be something like '1.10.0' or similar.
    value: ${{ steps.setup-fontist.outputs.fontist-version }}
  cache-hit:
    description: Whether or not Fontist was restored from the runner's cache or download anew.
    value: ${{ steps.setup-fontist.outputs.cache-hit }}

runs:
  using: node20
  main: dist/main.js
  post: dist/post.js
